[package]
name = "chordpro-parser"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
pest = "2.7"
pest_derive = "2.7"
ciborium = "0.2.2"
serde = { version = "1.0.213", features = ["derive"] }
wasm-minimal-protocol = "0.1.0"